### ISSUE TITLE
KeyError: 'LASER'

### ISSUE THREAD

**Issue by letnotimitateothers** [ceshine/textrank_demo#5]
Hello,

Nice work ! 👍 

I want to run it on my computer, but I keep getting this error below.
Any clue how to solve it ?
Thanks a lot.

***
(base) MacBook-Pro:textrank_demo$ python demo.py
WARNING: Logging before flag parsing goes to stderr.
W0614 13:32:38.135787 4410598848 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14
[dynet] random seed: 1234
[dynet] allocating memory: 32MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from summa_score_sentences_laser import summarize as summarize_laser
  File "/Users/Documents/GIT/textrank_demo/summa_score_sentences_laser.py", line 16, in <module>
    MODEL_PATH = Path(os.environ["LASER"]) / "models/"
  File "/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LASER'
***

**Comment by ceshine** [comment]
Hi! 

I've recently added [LASER](https://github.com/facebookresearch/LASER) as an alternative sentence encoder. It requires setting an environment variable "LASER" pointing to the LASER project folder (in this case, `LASER_PROJECT` under the project root. You can check out [Dockerfile.laser](https://github.com/ceshine/textrank_demo/blob/master/Dockerfile.laser_cpu) for more details. 

Sorry the LASER part is not really documented, as I've found tf-sentencepiece is not compatible with that Dockerfile, and had to maintain two separate dockerfile for LASER and Universal Sentence Encoder. It's just a mess.

You can also just use code in this tag [`before-laser`](https://github.com/ceshine/textrank_demo/tree/before-laser) if you're not intended to use LASER.

Cheers,
Ceshine

**Comment by ceshine** [comment]
I've modified the code so that the server will run despite the absence of LASER (but the LASER option on the page won't work, of course). Some brief instructions on building and using Docker images are also provided.

(BTW, at this moment `USE-xling` probably won't work out of box.)

I'm closing this issue for now. Feel free to comment on it if you experience any more difficulties.
